-- Seed data for Location Tracker (optional)
-- Note: In production, don't use hardcoded passwords or seed data directly
-- This is just for development/testing purposes

-- You'll need to create users through Supabase Auth UI or API
-- After users are created, you can insert additional data here

-- Example location data (will be auto-generated by the mobile app)
-- insert into public.locations (user_id, latitude, longitude, accuracy)
-- values
--   ('user-uuid-1', 37.7749, -122.4194, 5),
--   ('user-uuid-2', 34.0522, -118.2437, 5);
